/**
 * Ported faithfully from js/map-data.js (COUNCIL_TAX, STATION_BOROUGH,
 * getCouncilTax) — 2024/25 Band D annual rates, ranked cheapest to most
 * expensive across 33 London authorities. Source: GLA / individual
 * council published rates. Update both this file and the web version
 * together if council tax rates change.
 *
 * Generated programmatically from the source file rather than transcribed
 * by hand — a first hand-transcribed pass only captured 164 of 423 real
 * station entries (only read the first portion of a much longer file).
 * Verified: 33 boroughs, 423 unique stations, parses correctly.
 */

export const COUNCIL_TAX: Record<string, { annual: number; rank: number }> = {
  'Wandsworth': { annual: 845, rank: 1 },
  'Westminster': { annual: 871, rank: 2 },
  'City of London': { annual: 1017, rank: 3 },
  'Hammersmith and Fulham': { annual: 1471, rank: 4 },
  'Kensington and Chelsea': { annual: 1589, rank: 5 },
  'Barking and Dagenham': { annual: 1789, rank: 6 },
  'Newham': { annual: 1804, rank: 7 },
  'Havering': { annual: 1821, rank: 8 },
  'Bexley': { annual: 1832, rank: 9 },
  'Croydon': { annual: 1839, rank: 10 },
  'Sutton': { annual: 1851, rank: 11 },
  'Enfield': { annual: 1864, rank: 12 },
  'Waltham Forest': { annual: 1871, rank: 13 },
  'Hillingdon': { annual: 1889, rank: 14 },
  'Bromley': { annual: 1893, rank: 15 },
  'Redbridge': { annual: 1902, rank: 16 },
  'Harrow': { annual: 1918, rank: 17 },
  'Ealing': { annual: 1921, rank: 18 },
  'Hounslow': { annual: 1934, rank: 19 },
  'Barnet': { annual: 1952, rank: 20 },
  'Greenwich': { annual: 1961, rank: 21 },
  'Lewisham': { annual: 1974, rank: 22 },
  'Haringey': { annual: 1989, rank: 23 },
  'Merton': { annual: 1998, rank: 24 },
  'Southwark': { annual: 2001, rank: 25 },
  'Tower Hamlets': { annual: 2013, rank: 26 },
  'Hackney': { annual: 2019, rank: 27 },
  'Lambeth': { annual: 2034, rank: 28 },
  'Brent': { annual: 2041, rank: 29 },
  'Islington': { annual: 2058, rank: 30 },
  'Richmond upon Thames': { annual: 2119, rank: 31 },
  'Kingston upon Thames': { annual: 2201, rank: 32 },
  'Camden': { annual: 2289, rank: 33 },
};

export const STATION_BOROUGH: Record<string, string> = {
  'Abbey Road': 'Newham',
  'Abbey Wood': 'Greenwich',
  'Acton Central': 'Ealing',
  'Acton Main Line': 'Ealing',
  'Acton Town': 'Ealing',
  'Addington Village': 'Croydon',
  'Albany Park': 'Bexley',
  'Aldgate': 'City of London',
  'Aldgate East': 'Tower Hamlets',
  'Alexandra Palace': 'Haringey',
  'All Saints': 'Tower Hamlets',
  'Ampere Way': 'Croydon',
  'Angel': 'Islington',
  'Archway': 'Islington',
  'Arnos Grove': 'Enfield',
  'Arsenal': 'Islington',
  'Baker Street': 'Westminster',
  'Balham': 'Wandsworth',
  'Bank': 'City of London',
  'Barbican': 'City of London',
  'Barking': 'Barking and Dagenham',
  'Barkingside': 'Redbridge',
  'Barnehurst': 'Bexley',
  'Barnes': 'Richmond upon Thames',
  'Barnes Bridge': 'Richmond upon Thames',
  'Barnsbury': 'Islington',
  'Barons Court': 'Hammersmith and Fulham',
  'Battersea Park': 'Wandsworth',
  'Battersea Power Station': 'Wandsworth',
  'Beckton': 'Newham',
  'Becontree': 'Barking and Dagenham',
  'Beddington Lane': 'Croydon',
  'Belgrave Walk': 'Merton',
  'Bell Green': 'Lewisham',
  'Belsize Park': 'Camden',
  'Bermondsey': 'Southwark',
  'Berrylands': 'Kingston upon Thames',
  'Bethnal Green': 'Tower Hamlets',
  'Bexley': 'Bexley',
  'Bexleyheath': 'Bexley',
  'Blackfriars': 'City of London',
  'Blackheath': 'Greenwich',
  'Blackhorse Road': 'Waltham Forest',
  'Bond Street': 'Westminster',
  'Borough': 'Southwark',
  'Bounds Green': 'Haringey',
  'Bow Church': 'Tower Hamlets',
  'Bow Road': 'Tower Hamlets',
  'Bowes Park': 'Haringey',
  'Brentwood': 'Brentwood',
  'Brixton': 'Lambeth',
  'Brockley': 'Lewisham',
  'Brondesbury': 'Brent',
  'Brondesbury Park': 'Brent',
  'Buckhurst Hill': 'Epping Forest',
  'Caledonian Road': 'Islington',
  'Caledonian Road & Barnsbury': 'Islington',
  'Cambridge Heath': 'Tower Hamlets',
  'Camden Town': 'Camden',
  'Canada Water': 'Southwark',
  'Canary Wharf': 'Tower Hamlets',
  'Canning Town': 'Newham',
  'Cannon Street': 'City of London',
  'Canonbury': 'Islington',
  'Carshalton': 'Sutton',
  'Carshalton Beeches': 'Sutton',
  'Catford': 'Lewisham',
  'Catford Bridge': 'Lewisham',
  'Chadwell Heath': 'Barking and Dagenham',
  'Chalk Farm': 'Camden',
  'Chancery Lane': 'Camden',
  'Charing Cross': 'Westminster',
  'Charlton': 'Greenwich',
  'Chessington North': 'Kingston upon Thames',
  'Chessington South': 'Kingston upon Thames',
  'Chingford': 'Waltham Forest',
  'Chiswick': 'Hounslow',
  'Chiswick Park': 'Hounslow',
  'City Thameslink': 'City of London',
  'Clapham': 'Lambeth',
  'Clapham Common': 'Lambeth',
  'Clapham Junction': 'Wandsworth',
  'Clapham North': 'Lambeth',
  'Clapham South': 'Lambeth',
  'Clapton': 'Hackney',
  'Colliers Wood': 'Merton',
  'Covent Garden': 'Westminster',
  'Crofton Park': 'Lewisham',
  'Crossharbour': 'Tower Hamlets',
  'Croydon': 'Croydon',
  'Crystal Palace': 'Bromley',
  'Cutty Sark': 'Greenwich',
  'Cyprus': 'Newham',
  'Dagenham East': 'Barking and Dagenham',
  'Dagenham Heathway': 'Barking and Dagenham',
  'Dalston Junction': 'Hackney',
  'Dalston Kingsland': 'Hackney',
  'Debden': 'Epping Forest',
  'Denmark Hill': 'Southwark',
  'Deptford Bridge': 'Lewisham',
  'Devons Road': 'Tower Hamlets',
  'Dollis Hill': 'Brent',
  'Drayton Park': 'Islington',
  'Ealing Broadway': 'Ealing',
  'Ealing Common': 'Ealing',
  'Earls Court': 'Kensington and Chelsea',
  'Earlsfield': 'Wandsworth',
  'East Acton': 'Ealing',
  'East Croydon': 'Croydon',
  'East Dulwich': 'Southwark',
  'East Finchley': 'Barnet',
  'East Ham': 'Newham',
  'East India': 'Tower Hamlets',
  'East Putney': 'Wandsworth',
  'Edgware Road': 'Westminster',
  'Elephant & Castle': 'Southwark',
  'Elephant and Castle': 'Southwark',
  'Elm Park': 'Havering',
  'Eltham': 'Greenwich',
  'Elverson Road': 'Lewisham',
  'Embankment': 'Westminster',
  'Emerson Park': 'Havering',
  'Enfield Chase': 'Enfield',
  'Enfield Town': 'Enfield',
  'Epping': 'Epping Forest',
  'Erith': 'Bexley',
  'Essex Road': 'Islington',
  'Euston': 'Camden',
  'Euston Square': 'Camden',
  'Fairlop': 'Redbridge',
  'Farringdon': 'Islington',
  'Fenchurch Street': 'City of London',
  'Fieldway': 'Croydon',
  'Finchley Central': 'Barnet',
  'Finchley Road': 'Camden',
  'Finsbury Park': 'Islington',
  'Forest Gate': 'Newham',
  'Forest Hill': 'Lewisham',
  'Fulham Broadway': 'Hammersmith and Fulham',
  'Fulwell': 'Richmond upon Thames',
  'Gallions Reach': 'Newham',
  'Gidea Park': 'Havering',
  'Gipsy Hill': 'Lambeth',
  'Gloucester Road': 'Kensington and Chelsea',
  'Goodge Street': 'Camden',
  'Goodmayes': 'Redbridge',
  'Gospel Oak': 'Camden',
  'Grange Hill': 'Redbridge',
  'Grange Park': 'Enfield',
  'Great Portland Street': 'Westminster',
  'Green Park': 'Westminster',
  'Greenford': 'Ealing',
  'Greenwich': 'Greenwich',
  'Grove Park': 'Lewisham',
  'Gunnersbury': 'Hounslow',
  'Hackney Central': 'Hackney',
  'Hackney Downs': 'Hackney',
  'Hackney Wick': 'Hackney',
  'Haggerston': 'Hackney',
  'Hainault': 'Redbridge',
  'Hammersmith': 'Hammersmith and Fulham',
  'Hampstead': 'Camden',
  'Hanger Lane': 'Ealing',
  'Hanwell': 'Ealing',
  'Harlesden': 'Brent',
  'Harold Wood': 'Havering',
  'Harrow and Wealdstone': 'Harrow',
  'Harrow-on-the-Hill': 'Harrow',
  'Hatton Cross': 'Hillingdon',
  'Haydons Road': 'Merton',
  'Hayes & Harlington': 'Hillingdon',
  'Heathrow Terminal 4': 'Hillingdon',
  'Heathrow Terminal 5': 'Hillingdon',
  'Heathrow Terminals 2 & 3': 'Hillingdon',
  'Herne Hill': 'Lambeth',
  'Heron Quays': 'Tower Hamlets',
  'High Street Kensington': 'Kensington and Chelsea',
  'Highams Park': 'Waltham Forest',
  'Highbury & Islington': 'Islington',
  'Highbury and Islington': 'Islington',
  'Highgate': 'Haringey',
  'Hillingdon': 'Hillingdon',
  'Hither Green': 'Lewisham',
  'Holborn': 'Camden',
  'Honor Oak Park': 'Lewisham',
  'Hornchurch': 'Havering',
  'Hounslow': 'Hounslow',
  'Hounslow Central': 'Hounslow',
  'Hounslow East': 'Hounslow',
  'Hounslow West': 'Hounslow',
  'Hoxton': 'Hackney',
  'Hyde Park Corner': 'Westminster',
  'Ickenham': 'Hillingdon',
  'Ilford': 'Redbridge',
  'Island Gardens': 'Tower Hamlets',
  'Kennington': 'Lambeth',
  'Kensal Green': 'Brent',
  'Kensal Rise': 'Brent',
  'Kensington Olympia': 'Kensington and Chelsea',
  'Kentish Town': 'Camden',
  'Kenton': 'Harrow',
  'Kew Gardens': 'Richmond upon Thames',
  'Kidbrooke': 'Greenwich',
  'Kilburn': 'Brent',
  'King\'s Cross': 'Camden',
  'King\'s Cross St Pancras': 'Camden',
  'Kings Cross St Pancras': 'Camden',
  'Kingsbury': 'Brent',
  'Kingston': 'Kingston upon Thames',
  'Knightsbridge': 'Kensington and Chelsea',
  'Ladbroke Grove': 'Kensington and Chelsea',
  'Ladywell': 'Lewisham',
  'Lambeth North': 'Lambeth',
  'Lancaster Gate': 'Westminster',
  'Langdon Park': 'Tower Hamlets',
  'Langley': 'Slough',
  'Latimer Road': 'Kensington and Chelsea',
  'Lee': 'Lewisham',
  'Leicester Square': 'Westminster',
  'Lewisham': 'Lewisham',
  'Leyton': 'Waltham Forest',
  'Leyton Midland Road': 'Waltham Forest',
  'Leytonstone': 'Waltham Forest',
  'Limehouse': 'Tower Hamlets',
  'Liverpool Street': 'City of London',
  'London Bridge': 'Southwark',
  'London Fields': 'Hackney',
  'Loughborough Junction': 'Lambeth',
  'Loughton': 'Epping Forest',
  'Lower Sydenham': 'Lewisham',
  'Maidenhead': 'Royal Borough of Windsor and Maidenhead',
  'Manor House': 'Haringey',
  'Manor Park': 'Newham',
  'Mansion House': 'City of London',
  'Marble Arch': 'Westminster',
  'Maryland': 'Newham',
  'Marylebone': 'Westminster',
  'Maze Hill': 'Greenwich',
  'Mile End': 'Tower Hamlets',
  'Mill Hill East': 'Barnet',
  'Mitcham': 'Merton',
  'Mitcham Eastfields': 'Merton',
  'Mitcham Junction': 'Merton',
  'Monument': 'City of London',
  'Moorgate': 'City of London',
  'Morden': 'Merton',
  'Morden Road': 'Merton',
  'Morden South': 'Merton',
  'Mortlake': 'Richmond upon Thames',
  'Mottingham': 'Bromley',
  'Mudchute': 'Tower Hamlets',
  'Neasden': 'Brent',
  'New Addington': 'Croydon',
  'New Cross': 'Lewisham',
  'New Cross Gate': 'Lewisham',
  'New Malden': 'Kingston upon Thames',
  'Newbury Park': 'Redbridge',
  'Nine Elms': 'Wandsworth',
  'Norbiton': 'Kingston upon Thames',
  'North Acton': 'Ealing',
  'North Dulwich': 'Southwark',
  'North Harrow': 'Harrow',
  'North Wembley': 'Brent',
  'Northolt': 'Ealing',
  'Norwood Junction': 'Croydon',
  'Notting Hill Gate': 'Kensington and Chelsea',
  'Old Street': 'Islington',
  'Oxford Circus': 'Westminster',
  'Paddington': 'Westminster',
  'Palmers Green': 'Enfield',
  'Park Royal': 'Ealing',
  'Parsons Green': 'Hammersmith and Fulham',
  'Peckham': 'Southwark',
  'Peckham Rye': 'Southwark',
  'Perivale': 'Ealing',
  'Phipps Bridge': 'Merton',
  'Piccadilly Circus': 'Westminster',
  'Pimlico': 'Westminster',
  'Plaistow': 'Newham',
  'Plumstead': 'Greenwich',
  'Pontoon Dock': 'Newham',
  'Poplar': 'Tower Hamlets',
  'Pudding Mill Lane': 'Tower Hamlets',
  'Purley': 'Croydon',
  'Purley Oaks': 'Croydon',
  'Putney': 'Wandsworth',
  'Putney Bridge': 'Hammersmith and Fulham',
  'Queens Road Peckham': 'Southwark',
  'Queensbury': 'Harrow',
  'Queenstown Road': 'Wandsworth',
  'Ravenscourt Park': 'Hammersmith and Fulham',
  'Rayners Lane': 'Harrow',
  'Reading': 'Reading',
  'Rectory Road': 'Hackney',
  'Regent\'s Park': 'Westminster',
  'Regents Park': 'Westminster',
  'Richmond': 'Richmond upon Thames',
  'Romford': 'Havering',
  'Rotherhithe': 'Southwark',
  'Royal Oak': 'Westminster',
  'Ruislip': 'Hillingdon',
  'Ruislip Gardens': 'Hillingdon',
  'Ruislip Manor': 'Hillingdon',
  'Russell Square': 'Camden',
  'Sanderstead': 'Croydon',
  'Selhurst': 'Croydon',
  'Selsdon': 'Croydon',
  'Seven Kings': 'Redbridge',
  'Seven Sisters': 'Haringey',
  'Shadwell': 'Tower Hamlets',
  'Shenfield': 'Chelmsford',
  'Shepherd\'s Bush Market': 'Hammersmith and Fulham',
  'Shepherds Bush': 'Hammersmith and Fulham',
  'Shoreditch High Street': 'Tower Hamlets',
  'Sidcup': 'Bexley',
  'Sloane Square': 'Kensington and Chelsea',
  'Slough': 'Slough',
  'Snaresbrook': 'Redbridge',
  'South Acton': 'Ealing',
  'South Croydon': 'Croydon',
  'South Hampstead': 'Camden',
  'South Kensington': 'Kensington and Chelsea',
  'South Kenton': 'Brent',
  'South Ruislip': 'Hillingdon',
  'South Tottenham': 'Haringey',
  'South Wimbledon': 'Merton',
  'South Woodford': 'Redbridge',
  'Southall': 'Ealing',
  'Southwark': 'Southwark',
  'St Helier': 'Merton',
  'St James Park': 'Westminster',
  'St James\'s Park': 'Westminster',
  'St Paul\'s': 'City of London',
  'St Pauls': 'City of London',
  'Stamford Brook': 'Hounslow',
  'Stamford Hill': 'Hackney',
  'Star Lane': 'Newham',
  'Stepney Green': 'Tower Hamlets',
  'Stockwell': 'Lambeth',
  'Stoke Newington': 'Hackney',
  'Stonebridge Park': 'Brent',
  'Stratford': 'Newham',
  'Stratford International': 'Newham',
  'Strawberry Hill': 'Richmond upon Thames',
  'Streatham': 'Lambeth',
  'Streatham Common': 'Lambeth',
  'Streatham Hill': 'Lambeth',
  'Surbiton': 'Kingston upon Thames',
  'Surrey Quays': 'Southwark',
  'Sutton': 'Sutton',
  'Sutton Common': 'Sutton',
  'Swiss Cottage': 'Camden',
  'Sydenham': 'Lewisham',
  'Taplow': 'Buckinghamshire',
  'Temple': 'Westminster',
  'Thamesmead': 'Greenwich',
  'Therapia Lane': 'Croydon',
  'Theydon Bois': 'Epping Forest',
  'Tolworth': 'Kingston upon Thames',
  'Tooting': 'Wandsworth',
  'Tooting Bec': 'Wandsworth',
  'Tooting Broadway': 'Merton',
  'Tottenham': 'Haringey',
  'Tottenham Court Road': 'Camden',
  'Tottenham Hale': 'Haringey',
  'Tower Gateway': 'Tower Hamlets',
  'Tower Hill': 'Tower Hamlets',
  'Tufnell Park': 'Islington',
  'Tulse Hill': 'Lambeth',
  'Turnham Green': 'Hounslow',
  'Twickenham': 'Richmond upon Thames',
  'Upminster': 'Havering',
  'Upminster Bridge': 'Havering',
  'Upney': 'Barking and Dagenham',
  'Upper Clapton': 'Hackney',
  'Upton Park': 'Newham',
  'Uxbridge': 'Hillingdon',
  'Vauxhall': 'Lambeth',
  'Victoria': 'Westminster',
  'Waddon': 'Croydon',
  'Wallington': 'Sutton',
  'Walthamstow Central': 'Waltham Forest',
  'Walthamstow Queens Road': 'Waltham Forest',
  'Wandsworth': 'Wandsworth',
  'Wandsworth Common': 'Wandsworth',
  'Wandsworth Road': 'Lambeth',
  'Wandsworth Town': 'Wandsworth',
  'Wanstead': 'Redbridge',
  'Wanstead Park': 'Newham',
  'Wapping': 'Tower Hamlets',
  'Warren Street': 'Camden',
  'Waterloo': 'Lambeth',
  'Wembley': 'Brent',
  'Wembley Central': 'Brent',
  'Wembley Stadium': 'Brent',
  'West Brompton': 'Kensington and Chelsea',
  'West Croydon': 'Croydon',
  'West Drayton': 'Hillingdon',
  'West Dulwich': 'Lambeth',
  'West Ealing': 'Ealing',
  'West Finchley': 'Barnet',
  'West Ham': 'Newham',
  'West Hampstead': 'Camden',
  'West Kensington': 'Hammersmith and Fulham',
  'West Ruislip': 'Hillingdon',
  'West Silvertown': 'Newham',
  'Westbourne Park': 'Kensington and Chelsea',
  'Westcombe Park': 'Greenwich',
  'Westferry': 'Tower Hamlets',
  'Westminster': 'Westminster',
  'Whitechapel': 'Tower Hamlets',
  'Willesden Green': 'Brent',
  'Willesden Junction': 'Brent',
  'Wimbledon': 'Merton',
  'Wimbledon Chase': 'Merton',
  'Winchmore Hill': 'Enfield',
  'Wood Green': 'Haringey',
  'Wood Lane': 'Hammersmith and Fulham',
  'Wood Street': 'Waltham Forest',
  'Woodford': 'Redbridge',
  'Woodgrange Park': 'Newham',
  'Woolwich': 'Greenwich',
  'Woolwich Arsenal': 'Greenwich',
};

export function getCouncilTax(areaName: string): { borough: string; annual: number; rank: number } | null {
  const borough = STATION_BOROUGH[areaName];
  if (!borough) return null;
  const data = COUNCIL_TAX[borough];
  return data ? { borough, annual: data.annual, rank: data.rank } : null;
}
